# Generated by Django 3.2 on 2023-06-13 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissionconditionforcitizen',
            name='condition',
            field=models.TextField(verbose_name='Условие'),
        ),
    ]
