# Generated by Django 3.2 on 2022-06-19 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('image', models.ImageField(upload_to='common/', verbose_name='Изображение')),
                ('subtitle', models.CharField(max_length=255, verbose_name='Подзаголовок')),
                ('description', models.TextField(max_length=1000, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Приветственная страница для новых пользователей',
                'verbose_name_plural': 'Приветственная страница для новых пользователей',
            },
        ),
    ]
