# Generated by Django 3.2 on 2022-06-19 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Активно'), (2, 'Заблокировано')], verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Беседа',
                'verbose_name_plural': 'Беседы',
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(max_length=500, unique=True, verbose_name='Вопрос')),
                ('answer', models.TextField(verbose_name='Ответ')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='Позиция')),
            ],
            options={
                'verbose_name': 'Вопросы и Ответы',
                'verbose_name_plural': 'Вопросы и Ответы',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=1000, verbose_name='Текст')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Отправлено'), (2, 'Просмотрено')], default=1, verbose_name='Статус')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Удалено?')),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'От абитуриента'), (2, 'От администратора')], default=2, verbose_name='Тип')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='Отправлено в')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.conversation')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
            },
        ),
    ]
